### ISSUE TITLE
icons are too large

### ISSUE THREAD

**Issue by seagle0128** [mxgoldstein/emojify-logos#1]
icons are too large in my GNU Emacs 26.0.90 on macOS 10.13.1.

**Comment by mxgoldstein** [comment]
Hi there,

Thanks for your interest in the project.

Couple of questions:
1) Could you provide a screenshot?
2) Do you have this issue with all icons or just particular ones? If you're unsure could you please [download README.MD](https://github.com/mxgoldstein/emojify-logos/blob/master/README.MD) open it Emacs and check? That would help a lot.

~ mxgoldstein

**Comment by iqbalansari** [comment]
Hi @seagle0128,

It seems your Emacs is not compiled with `imagemagick` support, `emojify` should automatically resize the images if `imagemagick` is available. You can check it by running `(fboundp 'imagemagick-types)`, if the above returns `nil` then your Emacs is not compiled with `imagemagick`.

@mxgoldstein 

 Just a thought, maybe you can provide two set of icons
- One set which has icons resized to 22px which will be used when `imagemagick` is not available (22px if I remember correctly is the default font size in Emacs or something)
- Other set has the original icons which can be used when `imagemagick` is available in which `emojify` will handle the resizing of the icons

**Comment by seagle0128** [comment]
Thanks, @iqbalansari .
I checked on my env, `(fboundp 'imagemagick-types)` returns `t`.
And I tried to capture the screenshots. Unfortunately, `emojify-logos` doesn't work with Emacs 26.0.91 on macOS 10.13.3.
